language: go
go:
  - "1.13"
  - "1.14"
before_install:
   - go get github.com/xeipuuv/gojsonreference
   - go get github.com/xeipuuv/gojsonpointer
   - go get github.com/stretchr/testify/assert
script:
  - go test -coverpkg=./... -coverprofile=coverage.info -timeout=5s
after_succese:
  - bash <(curl -s https://codecov.io/bash)
